### ISSUE TITLE
unable to install on windows 10 andriod build tools

### ISSUE THREAD

**Issue by aquananu** [fuse-open/android-build-tools#11]
PS C:\WINDOWS\system32>     npm install android-build-tools

> android-build-tools@1.5.3 install C:\WINDOWS\system32\node_modules\android-build-tools
> xbash src/install.bash

Found JDK8 at C:\Program Files\Android\Android Studio\jre
Accepting licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

ERROR: Install failed.

Please read output for clues, or open an issue on GitHub (https://github.com/fuse-open/android-build-tools/issues).

Please note that JDK8 (not 9+) is required to install Android SDK. Get OpenJDK8 from https://adoptopenjdk.net/ and try again.
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! android-build-tools@1.5.3 install: `xbash src/install.bash`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the android-build-tools@1.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
PS C:\WINDOWS\system32>

**Comment by aquananu** [comment]
hi can anybody help please

**Comment by 2SIX6** [comment]
Similar issue, android-build-tools fails to install. 
___Log output below___
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   'android-build-tools',
0 verbose cli   '-g',
0 verbose cli   '-f',
0 verbose cli   '--prefix',
0 verbose cli   'C:\\Users\\#####\\AppData\\Roaming\\npm'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\#####\AppData\Roaming\npm\.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:C:\Users\#####\.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\#####\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 1ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 warn using --force Recommended protections disabled.
27 timing npm:load Completed in 11ms
28 timing arborist:ctor Completed in 2ms
29 timing idealTree:init Completed in 3ms
30 timing idealTree:userRequests Completed in 1ms
31 silly idealTree buildDeps
32 silly fetch manifest android-build-tools@*
33 http fetch GET 200 https://registry.npmjs.org/android-build-tools 494ms (cache revalidated)
34 silly placeDep ROOT android-build-tools@1.5.3 OK for:  want: *
35 silly fetch manifest xbash@^1.6.0
36 http fetch GET 200 https://registry.npmjs.org/xbash 406ms (cache revalidated)
37 timing idealTree:#root Completed in 907ms
38 silly placeDep node_modules/android-build-tools xbash@1.6.0 OK for: android-build-tools@1.5.3 want: ^1.6.0
39 silly fetch manifest which@^2.0.2
40 http fetch GET 200 https://registry.npmjs.org/which 47ms (cache revalidated)
41 timing idealTree:node_modules/android-build-tools Completed in 50ms
42 silly placeDep node_modules/android-build-tools which@2.0.2 OK for: xbash@1.6.0 want: ^2.0.2
43 silly fetch manifest isexe@^2.0.0
44 http fetch GET 200 https://registry.npmjs.org/isexe 41ms (cache revalidated)
45 timing idealTree:node_modules/android-build-tools/node_modules/xbash Completed in 47ms
46 silly placeDep node_modules/android-build-tools isexe@2.0.0 OK for: which@2.0.2 want: ^2.0.0
47 timing idealTree:node_modules/android-build-tools/node_modules/which Completed in 4ms
48 timing idealTree:node_modules/android-build-tools/node_modules/isexe Completed in 0ms
49 timing idealTree:buildDeps Completed in 1010ms
50 timing idealTree:fixDepFlags Completed in 0ms
51 timing idealTree Completed in 1017ms
52 timing reify:loadTrees Completed in 1018ms
53 timing reify:diffTrees Completed in 0ms
54 silly reify moves {}
55 timing reify:retireShallow Completed in 0ms
56 timing reify:createSparse Completed in 2ms
57 timing reify:loadBundles Completed in 0ms
58 silly audit bulk request {
58 silly audit   'android-build-tools': [ '1.5.3' ],
58 silly audit   xbash: [ '1.6.0' ],
58 silly audit   which: [ '2.0.2' ],
58 silly audit   isexe: [ '2.0.0' ]
58 silly audit }
59 timing reifyNode:node_modules/android-build-tools/node_modules/xbash Completed in 18ms
60 timing reifyNode:node_modules/android-build-tools Completed in 19ms
61 timing reifyNode:node_modules/android-build-tools/node_modules/which Completed in 19ms
62 timing reifyNode:node_modules/android-build-tools/node_modules/isexe Completed in 21ms
63 timing reify:unpack Completed in 21ms
64 timing reify:unretire Completed in 0ms
65 timing build:queue Completed in 1ms
66 timing build:link:node_modules/android-build-tools/node_modules/which Completed in 4ms
67 timing build:link:node_modules/android-build-tools/node_modules/xbash Completed in 4ms
68 timing build:link Completed in 4ms
69 info run android-build-tools@1.5.3 install node_modules/android-build-tools xbash src/install.bash
70 info run android-build-tools@1.5.3 install { code: 1, signal: null }
71 timing reify:rollback:createSparse Completed in 7ms
72 timing reify:rollback:retireShallow Completed in 0ms
73 timing command:install Completed in 1173ms
74 verbose stack Error: command failed
74 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
74 verbose stack     at ChildProcess.emit (node:events:390:28)
74 verbose stack     at maybeClose (node:internal/child_process:1064:16)
74 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
75 verbose pkgid android-build-tools@1.5.3
76 verbose cwd C:\Program Files\fuse X
77 verbose Windows_NT 10.0.22000
78 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "android-build-tools" "-g" "-f" "--prefix" "C:\\Users\\#####\\AppData\\Roaming\\npm"
79 verbose node v16.13.0
80 verbose npm  v8.1.0
81 error code 1
82 error path C:\Users\#####\AppData\Roaming\npm\node_modules\android-build-tools
83 error command failed
84 error command C:\WINDOWS\system32\cmd.exe /d /s /c xbash src/install.bash
85 error ERROR: 'bash.exe' was not found. This can be solved by installing Git.
85 error
85 error Please get Git from https://git-scm.com/downloads and try again.
86 verbose exit 1
_____END LOG______

It should be noted that git is installed, as well as node.js and I did an installation repair as a test when it failed to install the first time.

**Comment by mortend** [comment]
Recent versions of Android Studio ships with JDK 11 instead of JDK 8 like before, and the old SDK tools only work on JDK 8.

I have published a new version of this module with new SDK tools that work on JDK 11.

The installer should work next time you try.

Thanks for reporting this issue. :)
