### ISSUE TITLE
Fails to download

### ISSUE THREAD

**Issue by JSilva6** [fuse-open/android-build-tools#8]
Trying to install this package on a ARMv8 output an error with cmake. I already have a newer version of cmake (3.13.4)

> \> android-build-tools@1.4.0 install /usr/local/lib/node_modules/android-build-tools
> \> xbash install.bash
> 
> Accepting licenses
> Installing cmake;3.10.2.4988404
> Warning: Failed to find package cmake;3.10.2.4988404
> [===                                    ] 10% Computing updates...
> ERROR: Install failed.
> 
> Please read output for clues, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).
> 
> Please note that JDK8 (not 9+) is required to install Android SDK. Get OpenJDK8 from https://adoptopenjdk.net/ and try again.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! android-build-tools@1.4.0 install: \`xbash install.bash\`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the android-build-tools@1.4.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-05-27T18_31_20_518Z-debug.log
>

**Comment by JSilva6** [comment]
Also, I do have JDK8 on my system

**Comment by mortend** [comment]
Thanks for the report.

I checked in Android Studio and it looks like 3.10.2.4988404 is still the current and latest version available in SDK Manager.

It looks like your JDK is working because `sdkmanager` runs fine. We use `sdkmanager` in Android SDK to install packages, so maybe the download failure was just a temporary glitch on their end?

We can maybe try deleting old caches and then reinstall `android-build-tools`.
```
rm -rf ~/.android/
npm install android-build-tools -g
```

**Comment by JSilva6** [comment]
Ok, the generic workaround didnt worked.

Allow me to introduce you a bit more of background:

I'm using a Raspberry Pi 4 witch uses an armhf architeture. Is it possible it's not being able to get the cmake 3.10.2 due to being not avaliable to that architeture? (even if I DO have the 3.13 version)

Also, I'm not able to attempt to install your package without the --unsafe-perm flag, since even with root user i'm always taking a Permission Denied on mkdir for /root/ folder, even using chown on that folder. Is this also possible to be an issue?

**Comment by mortend** [comment]
Oh, cool. That's a bit exotic.

Unfortunately I am not able to develop for Raspberry Pi and this package is only tested on x86_64.

I am guessing [install.bash](https://github.com/mortend/android-build-tools/blob/master/src/install.bash) needs some adjustments to make this work. Maybe skip cmake 3.10.2 when running on arm, and set `HOME` to something else than `/root/`. I'm not sure where the Android SDK is supposed to be located on RPi?

I am happily welcoming PRs if you find a setup that works on RPi.
